### PR TITLE
Adds Deno in memory

### PR DESCRIPTION
**Pull request by kiwicopple**
I'm still figuring out the persisted version

### CODE REVIEW

**Comment by kiwicopple** [comment]
image


Hanging on the db creation, although I can see it's definitely creating the files:

image

**Comment by kiwicopple** [comment]
Might need to revisit this to get Deno storage working. Happy for you to merge this if you don't want to leave PRs hanging (or you can close if you don't want a partial doc)

**Review by samwillis — APPROVED** [review]
Thanks Paul!

let me know how you get on with Deno FS

**Comment by alexgleason** [comment]
I've narrowed down the issue to here: https://github.com/electric-sql/pglite/blob/9a508ac71f03f0512bc4d69b1229d13415fa1733/packages/pglite/src/index.ts#L188-L193

This code adds event listeners for `waiting` and `result`, but their handlers never get called in Deno. Since the handlers don't get called, the promise doesn't resolve.

These functions aren't getting called by wasm at all. console never logs:

image

**Comment by alexgleason** [comment]
@samwillis Would you mind taking a look at my discovery? :point_up: I came very close to figuring it out but got stuck after realizing the event handlers weren't firing. Any ideas what could be causing that?

**Comment by samwillis** [comment]
Absolutely, sorry I missed this 😬

Based on your description of await_query not being called, that suggests that Postgres hasn't fully initialised. It never reaches the point in its main loop where it reads user input.

Which file system were you trying, the in memory or the persisted one?

**Comment by alexgleason** [comment]
It works in-memory. I was trying to figure out how to get the persisted one working in Deno. :thinking:

**Comment by samwillis** [comment]
There seems to be issues with running the Emscripten nodefs under Deno, it's mentioned here: https://github.com/emscripten-core/emscripten/issues/13190

We are still on an older version of Emscripten, it maybe that it's fixed in a newer version.

**Comment by alexgleason** [comment]
If we can pinpoint the issue we can open a bug in Deno. They're aiming for 100% Node compatibility, so Emscripten should not need to add any special support.

**Pull request merged**
