### PR TITLE
contrib folder auto builder

### PR DESCRIPTION
**Pull request by pmp-p**
this cibuild step will build automatically extension folder found in src/contrib with currently exception of :
 sslinfo bool_plperl hstore_plperl hstore_plpython jsonb_plperl jsonb_plpython
 ltree_plpython pgcrypto sepgsql bool_plperl start-scripts uuid-ossp

### CODE REVIEW

**Comment by pmp-p** [comment]
added xml2 pgcrypto and uuid-ossp

**Comment by samwillis** [comment]
@pmp-p The build on this seems to be failing on uuid-ossp. I'm going to merge #131 as is, as it forked off this PR a couple commits back. Then we can get the others merged once these are working.

**Comment by pmp-p** [comment]
@samwillis i just forgot the uuid switch rebuild into pg core which is triggered from configure with `--with-uuid=ossp` should be fixed now

**Comment by pmp-p** [comment]
nope ossp-uid detection still not well supported by sdk, will turn off and fix later as sdk is a 2 hours rebuild ...

**Pull request merged**
