### PR TITLE
extra extensions building

### PR DESCRIPTION
**Pull request by pmp-p**
now EXTRA_EXT list in yml/env will control list of extensions built when calling "cibuild.sh extra"

using extra/vector.sh for reference ( use only core sdk like pg ).

test-build extra/postgis.sh  ( now use the extra wasm sdk ), still missing tests though

### CODE REVIEW

**Comment by pmp-p** [comment]
need some real postgis testing

**Comment by John-P** [comment]
I wouldn't mind giving this a test. Do you have any information about creating a test setup? I see that the bot comment says it is deployed, but I cannot see anything there.

**Comment by pmp-p** [comment]
merged from wasi branch

**Comment by pmp-p** [comment]
postgis build script is fully ready but compiler/linker is not yet

**Pull request closed without merging**
